// The inbox shell: a GitHub-backed browse screen with tabs, repo grouping, an
// action menu and drill-in overlays. Host-agnostic — the surface supplies the
// queries (`fetcher`), the drilled-in view (`detailFor`) and its own vocabulary.
export {
  App,
  ActionMenu,
  useActionMenu,
  CiStatusLine,
  layoutGHItems,
  whoseMove,
  insertRepoHeaders,
  sortItems,
  sortByRecency,
  repoPriority,
  relativeTime,
  explainItem,
  filterByOrigin,
  filterBySearch,
  filterByRepos,
  withoutItem,
  reposInSections,
  topLevelCount,
  truncate,
  buildActions,
  buildCheckoutCmd,
  resolveRepoPath,
  clipboard,
  openInTab,
  runInPane,
  runInPaneHorizontal,
  runHere,
  jumpToRepo,
  jumpToRepoPane,
  itermRun,
  drillCmd,
  moveCursor,
  fitCount,
  windowCount,
  maxViewStart,
  withHeaders,
  toCiStatusState,
  sameCiStatusState,
  COLS,
  type GHItem,
  type Standing,
  type GHDetail,
  type Section,
  type AnyItem,
  type RepoHeader,
  type SubgroupHeader,
  type ShowMore,
  type ShowLess,
  type TaskRow,
  type JiraTransition,
  type CiStatus,
  type CiStatusState,
  type Action,
  type ExplainSection,
  type DetailContext,
  type OriginSplit,
} from "./inbox.js"
export type { InboxExtension, ExtensionTarget } from "./extension.js"
export { readCache, writeCache } from "./cache.js"
export {
  configureInbox,
  inboxConfig,
  resetInboxConfig,
  profileOf,
  checkoutDirs,
  type InboxConfig,
  type RepoProfile,
} from "./config.js"
export {
  matchesFilter,
  parsePatterns,
  type RepoFilter,
} from "./filter.js"
